# /etc/rsyslog.conf configuration file for rsyslog
#
# For more information install rsyslog-doc and see
# /usr/share/doc/rsyslog-doc/html/configuration/index.html

#################
#### MODULES ####
#################

module(load="imuxsock" SysSock.Use="off" SysSock.Unlink="off")
module(load="imudp")

###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

#
# Where to place spool and state files
#
$WorkDirectory /tmp 

###############
#### RULES ####
###############

$template RemoteHost,"/home/runner/github-actions-runner/virt/work/%HOSTNAME%.log"

ruleset(name="paramiko_log"){
    action(type="omfile" file="/home/runner/github-actions-runner/virt/work/paramiko_debug.log")
}

ruleset(name="test_log"){
    action(type="omfile" file="/home/runner/github-actions-runner/virt/work/test_debug.log")
}

ruleset(name="remote_logging"){
    action(type="omfile" dynaFile="RemoteHost")
}

################
#### INPUTS ####
################

input(type="imudp" port="5140" ruleset="remote_logging")

input(type="imuxsock" Socket="/tmp/gha_paramiko_log.sock" ruleset="paramiko_log")
input(type="imuxsock" Socket="/tmp/gha_test_log.sock" ruleset="test_log")
