# /etc/rsyslog.conf configuration file for rsyslog
#
# For more information install rsyslog-doc and see
# /usr/share/doc/rsyslog-doc/html/configuration/index.html

#################
#### MODULES ####
#################

# provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="5140")

###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

#
# Where to place spool and state files
#
$WorkDirectory /tmp 

###############
#### RULES ####
###############

$template RemoteHost,"/home/runner/github-actions-runner/virt/work/%HOSTNAME%.log"

*.* ?RemoteHost
